2020-05-21 15:05:54,858 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTkwMDU5Njg0LjYxNTUzMTR9.Bm5CMMI81Y9Uzutf8MAo_ySV-T0vZlE2GekFqZ4eob4 [GET] [in c:\users\user\mblog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\mblog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\PycharmProjects\mblog\app\routes.py", line 197, in reset_password
    user = User.verify_reset_password_token(token)
  File "C:\Users\User\PycharmProjects\mblog\app\models.py", line 87, in verify_reset_password_token
    return User.quety.get(id)
AttributeError: type object 'User' has no attribute 'quety'
2020-05-21 15:06:54,149 INFO: Flaskblog startup [in C:\Users\User\PycharmProjects\mblog\app\__init__.py:53]
2020-05-21 15:56:32,152 INFO: Flaskblog startup [in C:\Users\User\PycharmProjects\mblog\app\__init__.py:53]
