2020-05-19 15:23:52,825 ERROR: Exception on /user/Зелень [GET] [in c:\users\user\mblog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\mblog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\mblog\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\mblog\app\routes.py", line 87, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\user\mblog\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\user\mblog\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\mblog\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\mblog\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\mblog\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\mblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\mblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\User\PycharmProjects\mblog\app\templates\user.html", line 25, in block "content"
    {{ user.followed.cont() }} подписок
jinja2.exceptions.UndefinedError: 'sqlalchemy.orm.dynamic.AppenderBaseQuery object' has no attribute 'cont'
2020-05-19 15:24:15,614 INFO: Flaskblog startup [in C:\Users\User\PycharmProjects\mblog\app\__init__.py:48]
